<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionRrenovationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('question_rrenovation')->insert([
            ///// ID : 1 Salle de bain  ////////
            ['rrenovation_id'=>'1','question_id' =>'1'],
            ['rrenovation_id'=>'1','question_id' =>'2'],
            ['rrenovation_id'=>'1','question_id' =>'3'],
            ['rrenovation_id'=>'1','question_id' =>'4'],
            ['rrenovation_id'=>'1','question_id' =>'5'],
            ['rrenovation_id'=>'1','question_id' =>'6'],
            ['rrenovation_id'=>'1','question_id' =>'7'],
            ['rrenovation_id'=>'1','question_id' =>'8'],
            ['rrenovation_id'=>'1','question_id' =>'9'],
            ['rrenovation_id'=>'1','question_id' =>'10'],
            ['rrenovation_id'=>'1','question_id' =>'11'],
            ['rrenovation_id'=>'1','question_id' =>'12'],
            ['rrenovation_id'=>'1','question_id' =>'13'],
            ['rrenovation_id'=>'1','question_id' =>'14'],
            ['rrenovation_id'=>'1','question_id' =>'15'],
            ['rrenovation_id'=>'1','question_id' =>'16'],
            ['rrenovation_id'=>'1','question_id' =>'17'],
            ['rrenovation_id'=>'1','question_id' =>'18'],
            ['rrenovation_id'=>'1','question_id' =>'20'],
            ['rrenovation_id'=>'1','question_id' =>'21'],
            ['rrenovation_id'=>'1','question_id' =>'22'],
            ['rrenovation_id'=>'1','question_id' =>'23'],
            ['rrenovation_id'=>'1','question_id' =>'24'],
            ['rrenovation_id'=>'1','question_id' =>'25'],
            ['rrenovation_id'=>'1','question_id' =>'26'],
            ['rrenovation_id'=>'1','question_id' =>'27'],
            ///// ID : 2 Cuisine  ////////
            ['rrenovation_id'=>'2','question_id' =>'1'],
            ['rrenovation_id'=>'2','question_id' =>'2'],
            ['rrenovation_id'=>'2','question_id' =>'3'],
            ['rrenovation_id'=>'2','question_id' =>'4'],
            ['rrenovation_id'=>'2','question_id' =>'5'],
            ['rrenovation_id'=>'2','question_id' =>'6'],
            ['rrenovation_id'=>'2','question_id' =>'7'],
            ['rrenovation_id'=>'2','question_id' =>'28'],
            ['rrenovation_id'=>'2','question_id' =>'29'],
            ['rrenovation_id'=>'2','question_id' =>'30'],
            ['rrenovation_id'=>'2','question_id' =>'31'],
            ['rrenovation_id'=>'2','question_id' =>'32'],
            ['rrenovation_id'=>'2','question_id' =>'13'],
            ['rrenovation_id'=>'2','question_id' =>'85'],
            ['rrenovation_id'=>'2','question_id' =>'33'],
            ['rrenovation_id'=>'2','question_id' =>'15'],
            ['rrenovation_id'=>'2','question_id' =>'86'],
            ['rrenovation_id'=>'2','question_id' =>'17'],
            ['rrenovation_id'=>'2','question_id' =>'18'],
            ['rrenovation_id'=>'2','question_id' =>'19'],
            ['rrenovation_id'=>'2','question_id' =>'20'],
            ['rrenovation_id'=>'2','question_id' =>'21'],
            ['rrenovation_id'=>'2','question_id' =>'22'],
            ['rrenovation_id'=>'2','question_id' =>'23'],
            ['rrenovation_id'=>'2','question_id' =>'26'],
            ['rrenovation_id'=>'2','question_id' =>'87'],
            ///// ID : 3 sols-murs-plafonds  ////////
            ['rrenovation_id'=>'3','question_id' =>'1'],
            ['rrenovation_id'=>'3','question_id' =>'2'],
            ['rrenovation_id'=>'3','question_id' =>'3'],
            ['rrenovation_id'=>'3','question_id' =>'4'],
            ['rrenovation_id'=>'3','question_id' =>'5'],
            ['rrenovation_id'=>'3','question_id' =>'13'],
            ['rrenovation_id'=>'3','question_id' =>'88'],
            ['rrenovation_id'=>'3','question_id' =>'33'],
            ['rrenovation_id'=>'3','question_id' =>'15'],
            ['rrenovation_id'=>'3','question_id' =>'89'],
            ['rrenovation_id'=>'3','question_id' =>'17'],
            ['rrenovation_id'=>'3','question_id' =>'90'],
            ['rrenovation_id'=>'3','question_id' =>'19'],
            ['rrenovation_id'=>'3','question_id' =>'91'],
            ['rrenovation_id'=>'3','question_id' =>'21'],
            ['rrenovation_id'=>'3','question_id' =>'22'],
            ['rrenovation_id'=>'3','question_id' =>'23'],
            ///// ID : 4 fenetres  ////////
            ['rrenovation_id'=>'4','question_id' =>'1'],
            ['rrenovation_id'=>'4','question_id' =>'34'],
            ['rrenovation_id'=>'4','question_id' =>'35'],
            ['rrenovation_id'=>'4','question_id' =>'36'],
            ['rrenovation_id'=>'4','question_id' =>'37'],
            ///// ID : 5 menuiseries intérieurs  ////////
            ['rrenovation_id'=>'5','question_id' =>'1'],
            ['rrenovation_id'=>'5','question_id' =>'2'],
            ['rrenovation_id'=>'5','question_id' =>'3'],
            ['rrenovation_id'=>'5','question_id' =>'4'],
            ['rrenovation_id'=>'5','question_id' =>'5'],
            ///// ID : 6 Toiture- charpente-combles  ////////
            ['rrenovation_id'=>'6','question_id' =>'1'],
            ['rrenovation_id'=>'6','question_id' =>'38'],
            ['rrenovation_id'=>'6','question_id' =>'39'],
            ['rrenovation_id'=>'6','question_id' =>'40'],
            ['rrenovation_id'=>'6','question_id' =>'41'],
            ['rrenovation_id'=>'6','question_id' =>'42'],
            ['rrenovation_id'=>'6','question_id' =>'43'],
            ['rrenovation_id'=>'6','question_id' =>'44'],
            ['rrenovation_id'=>'6','question_id' =>'45'],
            ///// ID : 7 isolation- chauffage-clim  ////////
            ['rrenovation_id'=>'7','question_id' =>'1'],
            ['rrenovation_id'=>'7','question_id' =>'93'],
            ['rrenovation_id'=>'7','question_id' =>'46'],
            ['rrenovation_id'=>'7','question_id' =>'47'],
            ['rrenovation_id'=>'7','question_id' =>'48'],
            ['rrenovation_id'=>'7','question_id' =>'49'],
            ['rrenovation_id'=>'7','question_id' =>'50'],
            ['rrenovation_id'=>'7','question_id' =>'43'],
            ['rrenovation_id'=>'7','question_id' =>'36'],
            ['rrenovation_id'=>'7','question_id' =>'37'],
            ///// ID : 8  Électricité  ////////
            ['rrenovation_id'=>'8','question_id' =>'1'],
            ['rrenovation_id'=>'8','question_id' =>'51'],
            ['rrenovation_id'=>'8','question_id' =>'52'],
            ['rrenovation_id'=>'8','question_id' =>'53'],
            ['rrenovation_id'=>'8','question_id' =>'54'],
            ['rrenovation_id'=>'8','question_id' =>'55'],
            ['rrenovation_id'=>'8','question_id' =>'56'],
            ['rrenovation_id'=>'8','question_id' =>'57'],
            ['rrenovation_id'=>'8','question_id' =>'58'],
            ['rrenovation_id'=>'8','question_id' =>'59'],
            ['rrenovation_id'=>'8','question_id' =>'60'],
            ['rrenovation_id'=>'8','question_id' =>'61'],
            ['rrenovation_id'=>'8','question_id' =>'62'],
            ['rrenovation_id'=>'8','question_id' =>'63'],
            ['rrenovation_id'=>'8','question_id' =>'64'],
            ['rrenovation_id'=>'8','question_id' =>'65'],
            ['rrenovation_id'=>'8','question_id' =>'66'],
            ['rrenovation_id'=>'8','question_id' =>'67'],
            ///// ID : 9  Autre  ////////
            ['rrenovation_id'=>'9','question_id' =>'1'],
            ['rrenovation_id'=>'9','question_id' =>'2'],
            ['rrenovation_id'=>'9','question_id' =>'3'],
            ['rrenovation_id'=>'9','question_id' =>'4'],
            ['rrenovation_id'=>'9','question_id' =>'5'],
            ///// ID : 10  Appartement  ////////
            ['rrenovation_id'=>'10','question_id' =>'1'],
            ['rrenovation_id'=>'10','question_id' =>'68'],
            ['rrenovation_id'=>'10','question_id' =>'92'],
            ['rrenovation_id'=>'10','question_id' =>'69'],
            ['rrenovation_id'=>'10','question_id' =>'70'],
            ['rrenovation_id'=>'10','question_id' =>'71'],
            ['rrenovation_id'=>'10','question_id' =>'4'],
            ['rrenovation_id'=>'10','question_id' =>'5'],
            ///// ID : 11  Maison  ////////
            ['rrenovation_id'=>'11','question_id' =>'1'],
            ['rrenovation_id'=>'11','question_id' =>'68'],
            ['rrenovation_id'=>'11','question_id' =>'92'],
            ['rrenovation_id'=>'11','question_id' =>'69'],
            ['rrenovation_id'=>'11','question_id' =>'70'],
            ['rrenovation_id'=>'11','question_id' =>'4'],
            ['rrenovation_id'=>'11','question_id' =>'5'],
            ///// ID : 12  Studio  ////////
            ['rrenovation_id'=>'12','question_id' =>'1'],
            ['rrenovation_id'=>'12','question_id' =>'72'],
            ['rrenovation_id'=>'12','question_id' =>'92'],
            ['rrenovation_id'=>'12','question_id' =>'69'],
            ['rrenovation_id'=>'12','question_id' =>'70'],
            ['rrenovation_id'=>'12','question_id' =>'71'],
            ['rrenovation_id'=>'12','question_id' =>'4'],
            ['rrenovation_id'=>'12','question_id' =>'5'],
            ///// ID : 13  Extension - Survélévation  ////////
            ['rrenovation_id'=>'13','question_id' =>'1'],
            ['rrenovation_id'=>'13','question_id' =>'73'],
            ['rrenovation_id'=>'13','question_id' =>'74'],
            ['rrenovation_id'=>'13','question_id' =>'71'],
            ['rrenovation_id'=>'13','question_id' =>'75'],
            ['rrenovation_id'=>'13','question_id' =>'76'],
            ['rrenovation_id'=>'13','question_id' =>'77'],
            ['rrenovation_id'=>'13','question_id' =>'78'],
            ['rrenovation_id'=>'13','question_id' =>'79'],
            ['rrenovation_id'=>'13','question_id' =>'37'],
            ///// ID : 14 Bar-Restaurant-Commerce  ////////
            ['rrenovation_id'=>'14','question_id' =>'1'],
            ['rrenovation_id'=>'14','question_id' =>'80'],
            ['rrenovation_id'=>'14','question_id' =>'81'],
            ['rrenovation_id'=>'14','question_id' =>'82'],
            ['rrenovation_id'=>'14','question_id' =>'84'],
            ['rrenovation_id'=>'14','question_id' =>'50']

            
        ]);
    }
}
